version: '3.9'

services:
  # project build setting
  api:
    image: f1rstdoc/prac-docker:latest
    # build:
    #   dockerfile: ./Dockerfile
    #   context: .
    ports:
      - 80:3000
    volumes:
      - ./:/app/
    # sciprt run
    command: ['sh', '-c', 'npm run start:prod']
  # mongoDB setting
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db/

volumes:
  mongo:
